### ISSUE TITLE
Error when running example.py

### ISSUE THREAD

**Issue by ultramizer** [HcDevel/SiriAPI8#10]
Hi

I have correctly installed SiriAPI through the zip download on my MacBook, and could compile everything. Now when i'm running "sudo python example.py" i get the following error after about 5 Seconds:

```
MacBook-Pro:SiriAPI8-master username$ sudo python example.py
8.0.1
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    SiriAPI.connect() #Connect to iCloud
  File "/Users/teemoe/Downloads/SiriAPI8-master/SiriAPI8/SiriAPI.py", line 43, in connect
    typ, data = self.connection.search(None, 'ALL', 'SUBJECT "' + self.keyword + '"') #Delete unhandled commands with keyword (TODO: deal with alternative execution in future)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 627, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 905, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: SEARCH command error: BAD ['Invalid Search criteria']
```

What am i doing wrong? If i try to make an error on purpose in my icloud login, it gives me a different error message, so that's not the issue. I tried editing notes and adding and deleting on my iphone and it's synced nearly in realtime. Do i need to have the Notes.app on OSX open and running all the time?

Thanks!

**Comment by RobinMeis** [comment]
You are running SiriAPI8 using Python 2.7. SiriAPI8 is only compatible with Python3. You will need to install Python3 and run the installation steps again with it.

**Comment by ultramizer** [comment]
Genius! I just found that out myself.
If you're using OSX, simply download Python 3 from here: https://www.python.org/downloads/release/python-342/

And then run the command using python3.

Cheers!
