### ISSUE TITLE
Verbindungsabbruch bei telnet

### ISSUE THREAD

**Issue by tom2341** [HcDevel/SiriAPI8#11]
Hallo,

super Programm hast du geschrieben, habe ein Problem hoffe du kannst mir helfen.
Möchte gern innerhalb des Programm mithilfe von telnet auf fhem zugreifen um dort ein befehl einzugeben. Aber sobald ich das Passwort für den Port eingebe verliert SiriAPI8 die Verbindung und meldet sich darauf neu an.

Ich kopier dir hiermal die Programmstücke rein vllt kannst du mir helfen:

import telnetlib
import sys

host="192.168.178.22"
port="7072"
pas="1234"                        #Passwort für telenet in fhem

def fernseher(q, wildcards):
       if 'an'== wildcards[0]:
             print ("Fernseher " + wildcards[0])
             tel=telnetlib.Telnet(host,port)
             tel.read_unitl("Password:")
             tel.write(pas +"\n")
             tel.write('set MAX_0ddb3 desiredTemperatur 22.0')+b"\n")
             tel.write(b"exit\n"

hab über Kommetare (#) herrausgefunden das der bei tel.write(pas...) also beim einloggen mit Password die Verbindung verliert und den Befehl dann nicht weiter ausführt.
Nur den Telnet teil über ein seperates Skript ausgeführt funktioniert.

**Comment by RobinMeis** [comment]
Ich kann hier leider keinen Support für jeden noch so kleinen Anwendungsbereich geben. Da ich auch deinen Anwendungsbereich nicht kenne und das auch nicht testen kann kann ich hier auch nicht helfen.

**Comment by RobinMeis** [comment]
so jetzt ist mir zufällig noch ein Problem eingefallen. Das ist ein Bug in deinem Code. SiriAPI sieht das aber aufgrund noch fehlerhaften error handlings als internen Fehler an und verbindet sich erneut. Da kannst du mal die Klammer am Ende deines codes machen, die Einrückung korrigieren und vielleicht nicht unbedingt die gewünschte Temperatur an den Fernseher schicken. Das ist jedenfalls ein Fehler in deinem Code und dazu kann ich so nichts näher sagen
