### ISSUE TITLE
Problem with calling functions

### ISSUE THREAD

**Issue by direk** [HcDevel/SiriAPI8#16]
Hi,

I mostly managed to make it working - siri is creating notes and after calling example script notes are being deleted. this gives me knowledge that there are connections established and script can find correct keyword.

Problem is that I do not see output from called command - even if my test functions should only print some text in console I gets nothing. Is there any debug option to check it? When I call function manually it works fine - only calling via SiriAPI.action.add gives no result at all.

**Comment by RobinMeis** [comment]
Currently there is no debugging option. I completely forgot to implement this but I already created an issue for this.

Can you post a function you want to be called and how you added this to the code?

**Comment by direk** [comment]
The code is very simple, but i do not get any result (even print text in console is missing)... I want to use siri to turn on and off my lights based on philips hue system.

from SiriAPI8.SiriAPI import *
import requests

def lampka_on(q, wildcards):
    r = requests.put("http://10.0.0.16/api/raspberrypi/lights/12/state",'{"on":true, "sat":255, "bri":255,"hue":25535}')
    print("Wlaczam swiatlo")

def lampka_off(q, wildcards):
    r = requests.put("http://10.0.0.16/api/raspberrypi/lights/12/state",'{"on":false, "sat":255, "bri":255,"hue":25535}')
    print("Wylaczam swiatlo")

SiriAPI = SiriAPI("xxx", "xxx")

SiriAPI.action.add([['lights on', '_'],['turn the light on','_']], lampka_on)
SiriAPI.action.add([['lights off', '*']], lampka_off)

print ("Version: " + SiriAPI.get_version())

SiriAPI.action.list()
SiriAPI.connect()
SiriAPI.disconnect()

**Comment by RobinMeis** [comment]
Is the version printed and can you see new notes on icloud.com?

**Comment by direk** [comment]
Yes and yes... I see note until I run script. After that note is being deleted.

**Comment by RobinMeis** [comment]
> I see note until I run script

Does this mean that you create a note and then you run the script? It deletes any note tagged with the keyword without handling it on startup. Only notes which are created while running the script will be handled.
Your code does not run when you create a note, right? You have to add input("Press key") between SirAPI.connect() and SiriAPI.disconnect() to keep the code running and then create a note.

**Comment by Kosta-Github** [comment]
I think the issue is, that the keyword is still part of the text that is used for matching.

@direk Try to add the keyword as prefix to your patterns, e.g., if your keyword is `iphone` (the default value), change them to: `iphone lights on` ...

@HcDevel why not using `regex` for the pattern matching?

[edit] I think this only happend to my local copy of this repo with some modifications where I ended up with a keyword in uppercase letters set in the SiriAPI object, which then was not "correctly" removed from the search string due to the case mismatch. Actually, that is exactly the behavior I am after... :-)

**Comment by boomli** [comment]
Hallo
Erstmal danke für deinen Einsatz, Coole Sache!

Nachdem ich nun Stunden verbraten habe, hoffe ich hier eine Lösung zu finden.
Wahrscheinlich habe ich etwas falsch verstanden und es ist ganz einfach..
Bei mir steht jedes Mal, wenn ich 'iPhone hello' in meine Notizen (von Hand) schreibe: 'No Action defined vor iPhone hello'..
Sogar mit der Standart-Example.py
Die Synchronisation funktioniert, aber er kann den Befehl nicht finden.

Kann jemand helfen?

Danke

**Comment by RobinMeis** [comment]
Das hello hat noch eine wildcard. Du musst dahinter noch einen Namen sagen, damit alle Bedingungen erfüllt sind und die Funktion ausgeführt wird.

**Comment by boomli** [comment]
Hallo
Das habe ich natürlich auch versucht.
Bsp.: iPhone hello test
Es kommt immer no Action definiert..
Funktioniert das 'find' nicht?

Folgender genauer Fehler:
root@osmc:/opt/SiriAPI8-master# python3 example.py
8.0.1
Press any key...
SiriAPI8 error: No action defined for iPhone hello test

**Comment by ddx87** [comment]
Das gleiche Problem habe ich ebenfalls... egal was ich auch mache, es kommt immer "No action defined for ......" :-/

Leider mein erster Kontakt mit Python... grob verstehen tu ich den Code, allerdings wirklich nur grob :-/

**Comment by ddx87** [comment]
Ok... es läuft nun bei mir! Ich habe dieses mal einfach alle Schritte die ich durchgeführt habe direkt notiert für den Fall, dass ich zu einer Lösung komme! Wenn ich ehrlich bin, habe ich nichts anders gemacht als bei der Installation selbst... dennoch hier die Steps (Kurzform: Lösche den SiriApi8 Ordner und führe die Steps in der Installationsanleitung durch)

1) cd ..
2) cd opt
3) git clone https://github.com/HcDevel/SiriAPI8.git
4) cd SiriApi8
5) sudo python3 setup.py install
6) ## Bearbeiten von example.py ##
7) python3 example.py

nach

1) Den SiriApi8 Ordner löschen
2) Wechsle in das Verzeichnis indem die Api liegen soll
3) Neuste Version von SiriApi8 runterladen -> git clone https://github.com/HcDevel/SiriAPI8.git
4) In den SiriApi8 Ordner wechseln (cd SiriApi8)
5) SiriApi8 Setup ausführen (es kommt die Meldung dass es bereits hinterlegt ist... stören wir uns nicht weiter dran :P) -> sudo python3 setup.py install
6) examples.py bearbeiten und eigene Anmeldedaten eingeben (mit der icloud emailadresse)
7) Starten des Scripts -> python3 examples.py

Der einzige Unterschied zur Erstinstallation ist wirklich nur, dass ich beim ersten mal beim Klonen erst im Root Verzeichnis war und anschließend den Ordner per WinScp in den Opt Ordner verschoben habe. Aber das KANN nicht der Fehler sein Ich hatte da noch nicht das Setup ausgeführt oder dergleichen... wirklich nur geklont, verschoben und dann das Setup ausgeführt.

Als nächstes werde ich mal eigene Befehle testen, bin aber ganz zuversichtlich... vorher ging ja nicht mal das "hello" example!

For the english people here: If you`re experiencing issues that "No action is defined for ****" then try following these steps wich helped me fixing this problem (Short Version: Delete the SiriApi8 folder and do the steps in the Installation Guide again):

1) Delete the SiriApi8 folder
2) Go in the directory you want to have the SiriApi8 folder
3) Get the newest Version of SiriApi8 -> git clone https://github.com/HcDevel/SiriAPI8.git
4) Go into the SiriApi8 folder -> cd SiriApi8
5) Start the SiriApi8 Setup (ignore the message that its already installed)
6) Edit the example.py only with your credentials
7) Start the Script -> python3 examples.py

I hope this will help you, too!

lG

Alex

**Comment by ddx87** [comment]
Nachtrag: Das Problem ist reproduzierbar wenn man bzw. wenn ich das Keyword ändere! Sobald ich wieder "iphone" dort eintrage, funktioniert es!

**Comment by boomli** [comment]
WOW, super! Vielen Dank für deine Hilfe! Nun funktioniert es tatsächlich!
Jetzt versuch ich mal das ding in den 'autostart' zu packen, damit es auch läuft wenn ich es nicht via putty aufrufe und sobald ich die session trenne wieder aufhört..
.. Weisst du das zufälligerweise auch noch? :-)

**Comment by ddx87** [comment]
Hey boomli,

ja klar das weiß ich wohl auch :)
Du musst die Datei rc.local bearbeiten und vor "exit 0" am ende folgendes hinzufügen:

python3 /opt/SiriAPI8/Siristeuerung.py &

den Pfad musst du natürlich für dich anpassen. Das & am Ende bewirkt, dass nicht gewartet wird bis das Python Script durchgelaufen ist.

Ich habe auch herausgefunden, dass man anscheinend zwangsweise alle Keywords klein schreiben muss!! Das mal so am Rande :)

**Comment by boomli** [comment]
Hey ddx87
Funktioniert einwandfrei, danke dir!
Das mit der kleinschreibung ist mir auch vor 10 Minuten aufgefallen..
Aber es läuft jetzt recht 'stabil' das ganze..!
Nochmals danke..

**Comment by ddx87** [comment]
Kein Thema, wenn du noch Hilfe benötigst, dann lass es mich wissen!
