### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by matthijsotterloo** [HcDevel/SiriAPI8#18]
How can i connect my iPhone to my server which is running this API?

**Comment by direk** [comment]
You don't. 
iPhone is storing notes on server and this application checks for them and if finds defined keywords, prtforms some action.

**Comment by matthijsotterloo** [comment]
Ohhh so i say for example: "Siri note turn lights on"
Server checks if note contains turn lights on and turns lights on?

2015-02-22 18:13 GMT+01:00 direk notifications@github.com:

**Comment by direk** [comment]
Basically yes, but you also need keyword (by default word "iphone")
