### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by xena68** [HcDevel/SiriAPI8#2]
On step 2.4, I received this error:
<code>sudo python3 setup.py install</code>
<code>
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
ImportError: No module named setuptools
</code>

**Comment by RobinMeis** [comment]
Which operating system do you use? You can install it on debian based systems using `sudo apt-get install python3-setuptools`. In general it is explained here: https://pypi.python.org/pypi/setuptools. I will add this to the documentation. If you use the general instructions make sure that you run python3 instead of python

**Comment by 10wei1000** [comment]
I have experienced the same problem. I use the newest version of Raspbian.

Sonst danke sehr für so ein wunderschönes Werk :)

**Comment by RobinMeis** [comment]
I was able to reproduce your problems on a clean raspian installation. I was able to solve the problem installing setuptools as described in my previous post using `sudo apt-get install python3-setuptools`

**Comment by 10wei1000** [comment]
Yes, I have already fixed it with help of your previous post , forgot to mention it. Thank you!

**Comment by devilsingh** [comment]
please tell me i,m getting this error again and again
sudo python3 setup.py install
 Traceback (most recent call last): File "setup.py", line 3, in from setuptools import setup ImportError: No module named setuptools. 
my files of siriapi8 are in a folder  location /home/pi/SiriAPI8..
i also copies file from inside the folder to /home/pi
but again this comes...
please guide me

**Comment by RobinMeis** [comment]
Did you follow the instructions on https://github.com/HcDevel/SiriAPI8/wiki/Installation#siriapi8-installation to solve this problem? Which operating system are you using?

**Comment by devilsingh** [comment]
yes sir, it all done problem solved when i read all solutions u write  but i,ve iPhone 4s with ios 8.3...and i want to use siri to control lights but it is not working. i,m using raspberry pi b model. can u give me very simple step by step solution for this...i will b very thankful

**Comment by devilsingh** [comment]
i reallly don't know how to add commands for this, so that if i ask siri anything then it will answer me what i feed in it.. also iCloud note sync is enabled

**Comment by RobinMeis** [comment]
Again, just read the documentation https://github.com/HcDevel/SiriAPI8/wiki/API-Documentation

**Comment by MacBookeur** [comment]
Hi,

First, thank you for the good job, it's very useful !
However, i have a problem with "sudo python3 setup.py install" on OS X Yosemite...
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup
ImportError: No module named setup tools
Of course, before posting, i read carefully documentation and Install issue #2, but no effect...
I have install setup tools with no errors "curl https://bootstrap.pypa.io/ez_setup.py -o - | python" but when i launch "sudo python3 setup.py install", same error !
I don't understand, can you help me please ?

Thanks in advance

**Comment by MacBookeur** [comment]
I finally found by installing "the get-pip.py Pip Script Installer"
Successfully installed pip-7.1.2 setuptools-18.3.1 wheel-0.26.0
After that, "sudo python3 setup.py install" on OS X Yosemite works :-)
I can test...
