### ISSUE TITLE
How do I use GET in this implementation

### ISSUE THREAD

**Issue by purceno** [HcDevel/SiriAPI8#21]
Hello!

In previous SiriAPI, you have used a file called command.py . In this file, we could use html.request and put the URL where the smarthome server would be using.

Now, I am unable to use it in the example.py file.

How to I open a page, or send a GET in this implementation?

Example: 
def hello(q, wildcards): #Answer function
    html.request('10.1.1.3:8082/TurnMyLightsON'
    print ("You said Hello to " + wildcards[0])

Thanks a lot!

**Comment by RobinMeis** [comment]
The html class has been removed from the source code and this way I also removed the included request function. It was an extra function without a lot of sense, so I decided to remove it without any replacement.
You can copy the code from https://github.com/HcDevel/Siri-API/blob/master/document.py#L44 but make sure that you import urllib.request

**Comment by purceno** [comment]
Hello!
I just checked one of your files "my-personal-example.py" and I guess it will work fine for me.
I will try.
Thanks a lot
