### ISSUE TITLE
getting rid of markdown

### ISSUE THREAD

**Issue by DokRaphael** [HcDevel/SiriAPI8#22]
Hi 
I just tested the SiriAPI and works nicely.
I have one little problem, from the example file I get a response with the markdowns

```
8.1.3
Press any key...
SiriAPI8 error: No action defined for <html><head></head><body>iphone hello you</body></html>
```

Where can I get rid of these ?

Thank you

**Comment by RobinMeis** [comment]
I never experienced such a problem. But I don't think that it is hard to fix. Which iOS version are you using?

**Comment by DokRaphael** [comment]
I am using iOS8.3.

Ok, my bad, I was writing a note on my mac in OSX Yosemite
