### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by druvolo** [HcDevel/SiriAPI8#24]
Hello. I am new to GitHub and I'm not sure if I am posting this in the correct location. I apologize if this is not the correct place for this post. 

I really have a question instead of an issue. I am trying to understand the use case of your program compared to what I am looking to accomplish. My ask is pretty basic. I wish to use Siri for home automation but specifically have keywords in Siri open url's to my home automation system. The URL will contain the function that needs to be performed. 

For example, if I were to ask Siri to turn on the master bedroom lights it would open a URL such as "http://myautomationsystrm.com/siricommand=turn&on&master&bedroom$lights". I have written a function in my home automation system that looks for keywords anywhere in the string so I don't need to perform that outside of my existing program. 

I realize Apple is very restrictive and I'm not new to the challenges of having IOS work outside of what Apple wants. I used to use Siriproxy for this and all of my old code still exists. I'm just trying to figure out how your program can help me with this use case. I have read your documentation but something isn't clicking for me. You mention a link to a video in your readme but the link wasn't listed. 

I thank you in advance for your time.

**Comment by RobinMeis** [comment]
So, you want to say a specific command like "turn on light in bedroom" and internally SiriAPI8 should access your HTTP, right?
This is no problem. For each defined command, you have to write a Python function which is called if the keywords are found in your note. You can open an URL using Python, so all you have to do is to write a function which does the HTTP request. I'm also doing this for my automation system.

My personal configuration including such a function: https://github.com/HcDevel/SiriAPI8/blob/master/my-personal-example.py

**Comment by druvolo** [comment]
Thank you very much for your quick reply. The part I am not understanding is how does the Siri request make it to your Api for processing. I am not a python programmer but I follow the concept of your example. I believe it was your video for the previous version of your api that showed the Siri requests requiring the word "Google" first. Is that still the case with version 8 or do all keywords get checked against your api?

Thanks again in advance.

**Comment by RobinMeis** [comment]
The video is old and I forgot to create a new one ;) Now notes are used, that's why you have to provide your icloud login credential to SiriAPI8. You have to create a note by saying create note + keyword (by default siri) + your command

**Comment by RobinMeis** [comment]
No response - closed
