### ISSUE TITLE
IMAP problem

### ISSUE THREAD

**Issue by accloginsell** [HcDevel/SiriAPI8#29]
Hi all,

i have the following problem:

./example.py  
8.0.2  
Traceback (most recent call last):  
  File "./example.py", line 14, in <module>  
    SiriAPI.connect() #Connect to iCloud  
  File "/root/SiriAPI8/SiriAPI8/SiriAPI.py", line 50, in connect  
    typ, data = self.connection.search(None, 'ALL', 'SUBJECT "' + self.keyword + '"') #Delete unhandled commands with key
word (TODO: deal with alternative execution in future)  
  File "/usr/lib/python2.7/imaplib.py", line 627, in search  
    typ, dat = self._simple_command(name, *criteria)  
  File "/usr/lib/python2.7/imaplib.py", line 1070, in _simple_command  
    return self._command_complete(name, self._command(name, *args))  
  File "/usr/lib/python2.7/imaplib.py", line 905, in _command_complete  
    raise self.error('%s command error: %s %s' % (name, typ, data))  
imaplib.error: SEARCH command error: BAD ['Unexpected quoted string in SEARCH command']                                  

Can someone helps me?

Regards
Nico

**Comment by RobinMeis** [comment]
SiriAPI8 is a Python3 program, so run it using Python3. Root is not
required to run SiriAPI8.

On 07/20/2015 01:29 PM, accloginsell wrote:

> Hi all,
> 
> i have the following problem:
> 
> ./example.py
> 
> 8.0.2
> 
> Traceback (most recent call last):
> 
> File "./example.py", line 14, in
> 
> SiriAPI.connect() #Connect to iCloud
> 
> File "/root/SiriAPI8/SiriAPI8/SiriAPI.py", line 50, in connect
> 
> typ, data = self.connection.search(None, 'ALL', 'SUBJECT "' +
> self.keyword + '"') #Delete unhandled commands with key
> word (TODO: deal with alternative execution in future)
> 
> File "/usr/lib/python2.7/imaplib.py", line 627, in search
> 
> typ, dat = self._simple_command(name, *criteria)
> 
> File "/usr/lib/python2.7/imaplib.py", line 1070, in _simple_command
> 
> return self._command_complete(name, self._command(name, *args))
> 
> File "/usr/lib/python2.7/imaplib.py", line 905, in _command_complete
> 
> raise self.error('%s command error: %s %s' % (name, typ, data))
> 
> imaplib.error: SEARCH command error: BAD ['Unexpected quoted string in
> SEARCH command']
> 
> Can someone helps me?
> 
> Regards
> Nico
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HcDevel/SiriAPI8/issues/29.

## 

---

Öffentlicher PGP Schlüssel: http://blog.smartnoob.de/pgp-schluessel/

**Comment by RobinMeis** [comment]
No response - closed
