### ISSUE TITLE
Sorry, but the example.py seems doesn't work...

### ISSUE THREAD

**Issue by 10wei1000** [HcDevel/SiriAPI8#3]
Change your Email address to your iCloud Mail address and the password
// I used my iCloud Mail and the password of my Apple ID, is it right?

Now you can run example.py as described in the installation instructions
// Output:
// ~/SiriAPI8 $ sudo python3 example.py
// 8.0.0
// Press any key...

Open Siri and say create note iphone hello anybody. Also try to say other names than anybody
// I used Siri and the note was created, but the Terminal has no change...

Need your help, thanks!

**Comment by RobinMeis** [comment]
Did you check if iCloud sync is enabled? Can you see the note when you access icloud.com and sign in?
By the way, did my solution in issue #2  work?

Edit: I tried the example.py and it worked without problems

**Comment by 10wei1000** [comment]
the iCloud sync of Notes is already enabled. But I can't see the note i created with Siri.

Your solution in issue #2 works :+1:

**Comment by RobinMeis** [comment]
How long have you enabled iCloud sync? Maybe a reboot of your device helps. Obviously SiriAPI8 can't see the note because it isn't synced. Another question: Are you using the correct account?

**Comment by 10wei1000** [comment]
It has always been enabled. I tried reboot, but I still can’t see the note I created with Siri. I have tried delete a Note on my iPhone, too. Then I saw it was removed immediately from iCloud (I logged in using browser on my mac). And I  have created another one (just input it, not using Siri), which not displayed in iCloud jet, either. I think the sync of the new notes is not in real time, but the delete do. So strange. I will see tomorrow, wether the new notes are synced.

The account is the Apple ID which I use on my iPhone, too. The password in the example.py should be the password of my Apple ID, right?

**Comment by RobinMeis** [comment]
Yes that's right. If your credentials would be wrong you would get an exception. I found out that there are some problems with syncing between iOS8 and Mac OS. Maybe you can find a solution here: icloud notes not syncing ios 8 site:apple.com

**Comment by xena68** [comment]
I had the same problem and found that the default Note account was my gmail account. On iOS8, I went to settings>Notes and changed the default account to iCloud and my notes started showing up in iCloud.
