### ISSUE TITLE
No action defined

### ISSUE THREAD

**Issue by Chris0808** [HcDevel/SiriAPI8#4]
the example.py reads, analysis and deletes the note on iCloud.
But it only comes to the **error** function, and q is the complete note "iphone hello anybodys name".
Unfortunately it says, No action defined for "...".
I could not figure out yet what's the problem for this and how the program ends at the error function.

**Comment by Chris0808** [comment]
ok, with the new version of search.py the problem is fixed now :)

**Comment by RobinMeis** [comment]
I didn't change the search.py. Which new version do you mean?

**Comment by Chris0808** [comment]
25th of January, I Downloaded the zip before maybe it was an old version, I am not sure what was the reason, because I could not figure out yet how search.py worked. I need some time to read and understand the code, because I have never worked with Python before, but I will let You know if I know more.
