### ISSUE TITLE
get_version is not defined

### ISSUE THREAD

**Issue by xena68** [HcDevel/SiriAPI8#5]
Installed setuptools per your issue response and installed successfully.  Thanks!

Try to run examply.py and receive the following error:

~/SiriAPI8 $ sudo python3 example.py
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    print(get_version())
NameError: name 'get_version' is not defined

If I comment out line 7, it runs fine and I am able to execute the hello world example.

**Comment by xena68** [comment]
Solved:

Changed <code>print(get_version())</code> to
<code>print(SiriAPI.get_version())</code>

**Comment by RobinMeis** [comment]
Thank you for the report. I already new about the bug and it had been fixed. I think you had an old version of SiriAPI8.
