### ISSUE TITLE
Redirect to browser

### ISSUE THREAD

**Issue by xena68** [HcDevel/SiriAPI8#6]
First -- Great job on the program!  I was able to use my iPhone 6 to send commands to my home automation system!

Second, with SiriAPI I also used the document class to do things like open netflix.com with a search on a wildcard.  How would I do this with SiriAPI8?  Here is what I used in SiriAPI:

def addmovietonetflix(self, q, wildcards):
    html = document(self.connection)
    html.title("SiriAPI")
    html.outgoing(q)
    html.redirect("http://dvd.netflix.com/Search?v1=" + wildcards[0])
    html.send()

**Comment by RobinMeis** [comment]
It is not possible to redirect to any URL or give a response because Siri doesn't open a web browser or something else I could modify. The only possibility is to use a push notification service like Pushover and open the notification.

**Comment by xena68** [comment]
I'm successfully using prowl (http://www.prowlapp.com/) and prowlpy to send notifications to my iphone.  I did have to upgrade prowlpy to python 3 to get it to work.  Very slick.
