### ISSUE TITLE
iCloud login fail

### ISSUE THREAD

**Issue by email277** [HcDevel/SiriAPI8#9]
Hallo,

Hoffe du kannst mir helfen. Ich habe SiriAPI8 nach deiner Anleitung installiert und dann in der example.py meine Email und das Passwort hinterlegt. Wenn ich die Datei dann in der Konsole mit Python 3 ausführe, zeigt er mir erst die Version (8.0.1) an, bricht das Programm aber dann ab und sagt mir als Fehlermeldung: Login to iCloud failed. Check user credential.
Habe aber Emailadresse und Passwort richtige eingetragen.

**Comment by RobinMeis** [comment]
Hast du eine Apple Email Adresse eingeben?

**Comment by email277** [comment]
Die Emailadresse mit der ich mich am pc über den Webbrowser bei iCloud anmelde. .....@hotmail.de

**Comment by email277** [comment]
Ok hab mir eine iCloud Email erstellt @icloud.com. Jez bekommt er beim ausführen der example Datei aber einen anderen Fehler:
imaplib.error: commad SEARCH illegal in state AUTH, only allowed in state SELECTED

**Comment by RobinMeis** [comment]
Hast du schonmal irgendwann apps auf deinem I installiert?

**Comment by RobinMeis** [comment]
Und ist die Synchronisation von Notizen über die iCloud aktiviert?

**Comment by email277** [comment]
Ja habe es gesehen war mein Fehler. Nochmals Respekt fürs Programme habe es geschafft eine led zusteuern. Als nächstes mal mit ner Lampe versuchen. Ziel ist es irgendwann den Fernseher über IR zusteuern.
